   - name: variables
     hosts: web
     vars:
       URL: google.com
     tasks:
       - name: print variable
         ansible.builtin.debug:
           msg: URL = {{URL}}

       - name: print variable
         ansible.builtin.debug:
           msg: URL = {{URL}}
         vars:
           msg: tasks.goggle.com


